export const CollectionsData = [
  {
    id: 1,
    mainImg: "",
    image1: "http://localhost:3000/images/popular image/image1/Rectangle1.png",
    image2: "http://localhost:3000/images/popular image/image1/Rectangle2.png",
    image3: "http://localhost:3000/images/popular image/image1/Rectangle3.png",
    image4: "http://localhost:3000/images/popular image/image1/Rectangle4.png",
    tag: "People",
    view: "144",
  },
  {
    id: 2,
    mainImg: "",
    image1: "http://localhost:3000/images/popular image/image2/Rectangle1.png",
    image2: "http://localhost:3000/images/popular image/image2/Rectangle2.png",
    image3: "http://localhost:3000/images/popular image/image2/Rectangle3.png",
    image4: "http://localhost:3000/images/popular image/image2/Rectangle4.png",
    tag: "Nature",
    view: "7k",
  },
  {
    id: 3,
    mainImg: "",
    image1: "http://localhost:3000/images/popular image/image3/Rectangle1.png",
    image2: "http://localhost:3000/images/popular image/image3/Rectangle2.png",
    image3: "http://localhost:3000/images/popular image/image3/Rectangle3.png",
    image4: "http://localhost:3000/images/popular image/image3/Rectangle4.png",
    tag: "History",
    view: "431",
  },
];
