export const SampleDesignData = [
  {
    id: 7,
    img: "http://localhost:3000/images/sample/profile.png",
    title: "Profile Page , You must login for this page",
    date: "March 3, 2023",
    link: `/profile/user-email`,
  },
  {
    id: 6,
    img: "http://localhost:3000/images/sample/Products.png",
    title: "Products page, fetch data of API",
    date: "February 15, 2023",
    link: "/products",
  },
  {
    id: 5,
    img: "http://localhost:3000/images/sample/login2.png",
    title: "Login page",
    date: "February 6, 2023",
    link: "/login-page",
  },
  {
    id: 4,
    img: "http://localhost:3000/images/sample/signUp.png",
    title: "Sign up user, link in the user list",
    date: "February 2, 2023",
    link: "/sign-up",
  },
  {
    id: 3,
    img: "http://localhost:3000/images/sample/userList.png",
    title: "User list with search input",
    date: "February 1, 2023",
    link: "/user-list",
  },
  {
    id: 2,
    img: "http://localhost:3000/images/sample/collections.PNG",
    title: "Popular Collections",
    date: "january 31, 2023",
    link: "/collections",
  },
  {
    id: 1,
    img: "http://localhost:3000/images/sample/login.PNG",
    title: "Login page by password after user authenticated",
    date: "january 30, 2023",
    link: "/login",
  },
];
