import { UserType } from "../../typing";

export const UserListData: UserType[] = [
  {
    id: 1,
    img: "http://localhost:3000/images/userList/user1.png",
    firstname: "Lelah",
    lastname: "Nichols",
    city: "Troy",
    country: "MI",
    detail: "Troy, MI",
    password: "123456",
    email: "lelah.nichols@mail.com",
    fav: ["clothes", "stem"],
  },
  {
    id: 2,
    img: "http://localhost:3000/images/userList/user2.png",
    firstname: "Jesus",
    lastname: "Weiss",
    city: "Fort worth",
    country: "TX",
    detail: "Fort Worth, TX",
    password: "123456",
    email: "jesus.weiss@mail.com",
    fav: ["headset", "gadget", "speed", "winter"],
  },
  {
    id: 3,
    img: "http://localhost:3000/images/userList/user3.png",
    firstname: "Annie",
    lastname: "Rice",
    city: "Austin",
    country: "TX",
    detail: "Austin, TX",
    password: "123456",
    email: "annie.rice@mail.com",
    fav: ["road", "mountain", "trip", "earth", "nature"],
  },
  {
    id: 4,
    img: "http://localhost:3000/images/userList/user4.png",
    firstname: "Robert",
    lastname: "Brower",
    city: "Cincinnati",
    country: "OH",
    detail: "Cincinnati, OH",
    password: "123456",
    email: "robert.brower@mail.com",
    fav: ["Maintenance", "gears", "frames", "repair"],
  },
  {
    id: 5,
    img: "http://localhost:3000/images/userList/user5.png",
    firstname: "Amy",
    lastname: "Campbell",
    city: "Warrior",
    country: "AL",
    detail: "Warrior, AL",
    password: "123456",
    email: "amy.campbell@mail.com",
    fav: ["music", "disks"],
  },
  {
    id: 6,
    img: "http://localhost:3000/images/userList/user6.png",
    firstname: "Anthony",
    lastname: "S.Morin",
    city: "Lyndhurst",
    country: "NJ",
    detail: "Lyndhurst",
    password: "123456",
    email: "anthony.morin@mail.com",
    fav: ["vintage", "electric"],
  },
];
